name: Build standalone launcher for Windows

on: [push, pull_request]

jobs:
  compile:
    runs-on: windows-2019
    name: Compile
    steps:
      - uses: actions/checkout@master
        #with:
        #  submodules: true
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 16
          java-package: jdk+fx
      - name: Build Java runtime image
        run: jlink.exe --add-modules java.base,java.desktop,java.management,javafx.base,javafx.controls,javafx.fxml --compress=2 --strip-debug --no-header-files --no-man-pages --output chunkyjava
      #- name: Build Chunky launcher
      #  run: .\gradlew.bat :launcher:jar --stacktrace
      #  working-directory: ./chunky
      - uses: suisei-cn/actions-download-file@v1
        id: launcherjar
        name: Download the file
        with:
          url: https://chunkyupdate.lemaik.de/ChunkyLauncher.jar
          target: jars
      - name: Build binary
        run: jpackage.exe --runtime-image chunkyjava --input jars/ --main-jar ${{ steps.launcherjar.outputs.filename }} --output chunkyImage
      - uses: actions/upload-artifact@v2
        with:
          name: chunky-launcher-windows
          path: ./chunkyImage/**/*
